server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/login/**, /user/**

        # Product Service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**, /category/**

        # Invoice Service
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/invoice/**, /cart-item/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
