spring.application.name=invoice
server.port=8084
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.profiles.active=local

# Swagger
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none

# URL del product service para llamadas inter-servicio
product.service.url=http://localhost:8080