spring.application.name=invoice-service
server.port=8084
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.profiles.active=local

# URL del product service para llamadas inter-servicio
product.service.url=http://localhost:8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Actuator — endpoints para Admin Server
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Swagger
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none